### PR TITLE
Make ec_ arithmetic more consistent and add documentation

### LINKED ISSUE #671: Make ec_ arithmetic more consistent and add documentation
As brought up by @afk11 on #secp256k1 there are a couple of undocumented and inconsistent surprises in the ec arithmetic functions (that is `secp256k1_ec_pub/privkey_neg`, `_tweak_add` and `tweak_mul`.

In particular:

1. Right now, `ec_privkey_neg`, `ec_privkey_tweak_add` and `ec_privkey_tweak_mul` do not fail if the seckey is invalid, but they may give unexpected results in that case (f.e. #488). In order to avoid that, the user should call `ec_seckey_verify` before calling these functions, but that's not documented. Alternatively, these functions could call `ec_seckey_verify` themselves. In any case we should define what a valid `seckey` is (in the documentation of `ec_seckey_verify` for example) and refer to that in the argument documentation of other functions.
2. `ec_privkey_tweak_add` and `ec_privkey_tweak_mul` can fail (return 0). As a result the seckey argument will be zeroized. This is not documented. There's conflicting ideas whether this is a good idea:
    * "preserving any entropy in the bad input is the safer behaviour (e.g. the data in it might get fed elsewhere into some rng hash or something)" (@gmaxwell in #668).
    * vs.
        ```
        17:25 < andytoshi> leaving it alone sounds very dangerous, presumably the original key will "work" in subsequent algos
        17:25 < andytoshi> while a 0 key is pretty visible and will cause failures pretty-much no matter what you do with it
        ```
        However, right now we wouldn't detect the 0 key in `ec_privkey_tweak_add` and `tweak_mul`

3. `privkey_tweak_add` and `privkey_tweak_mul` fail if the resulting privkey is 0 but not if it overflows. That's not ideal because you won't be able to sign for it. Additionally, the documentation for `privkey_tweak_add` is wrong: `returns: [...] 0 the resulting private key [...] would be invalid (only when the tweak is the complement of the corresponding private key)` (same for `pubkey_tweak_add`). An overflowing private key is also invalid.
4. All this behavior should be tested
5. See #670 for naming improvements (seckey vs. privkey)

### PR DESCRIPTION
**Pull request by jonasnick**
Fixes #671. Supersedes #668.

This PR unifies handling of invalid secret keys by introducing a new function `scalar_set_b32_secret` which returns false if the b32 overflows or is 0. By using this in `privkey_{negate, tweak_add, tweak_mul}` these function will now return 0 if the secret key is invalid which matches the behavior of `ecdsa_sign` and `pubkey_create`.

Instead of deciding whether to zeroize the secret key on failure, I only added documentation for now that the value is undefined on failure.

### CODE REVIEW

File: include/secp256k1.h [hunk 1]
```diff
@@ -599,9 +602,10 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_negate(
 
 /** Tweak a private key by adding tweak to it.
  * Returns: 0 if the tweak was out of range (chance of around 1 in 2^128 for
- *          uniformly random 32-byte arrays, or if the resulting private key
- *          would be invalid (only when the tweak is the complement of the
- *          private key). 1 otherwise.
+ *          uniformly random 32-byte arrays, or if the given private key is
+ *          invalid according to secp256k1_ec_seckey_verify, or if the resulting
+ *          private key would be invalid (only when the tweak is the complement
```
Comment (real-or-random) [inline include/secp256k1.h]: Maybe "negated private key" instead of "complement"?

Is this really the only case? What about overflows?

File: include/secp256k1.h [hunk 2]
```diff
@@ -614,9 +618,10 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_privkey_tweak_add(
 
 /** Tweak a public key by adding tweak times the generator to it.
  * Returns: 0 if the tweak was out of range (chance of around 1 in 2^128 for
- *          uniformly random 32-byte arrays, or if the resulting public key
- *          would be invalid (only when the tweak is the complement of the
- *          corresponding private key). 1 otherwise.
+ *          uniformly random 32-byte arrays, or if the given private key is
+ *          invalid according to secp256k1_ec_seckey_verify, or if the resulting
+ *          public key would be invalid (only when the tweak is the complement
```
Comment (real-or-random) [inline include/secp256k1.h]: same here

File: src/secp256k1.c [hunk 3]
```diff
@@ -526,7 +526,9 @@ int secp256k1_ec_privkey_negate(const secp256k1_context* ctx, unsigned char *sec
     VERIFY_CHECK(ctx != NULL);
     ARG_CHECK(seckey != NULL);
 
-    secp256k1_scalar_set_b32(&sec, seckey, NULL);
+    if(!secp256k1_scalar_set_b32_seckey(&sec, seckey)) {
```
Comment (real-or-random) [inline src/secp256k1.c]: nit: spacing

File: include/secp256k1.h (hunk 1 above)
Comment (real-or-random) [reply include/secp256k1.h]: This should also document what the valid range for a tweak is? (I guess every scalar?)

File: include/secp256k1.h [hunk 4]
```diff
@@ -584,7 +584,8 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_create(
  *           secp256k1_ec_seckey_verify. 1 otherwise
  *  Args:   ctx:        pointer to a context object
  *  In/Out: seckey:     pointer to the 32-byte private key to be negated. The private
- *                      key should be valid according to secp256k1_ec_seckey_verify
+ *                      key should be valid according to secp256k1_ec_seckey_verify.
+ *                      Value becomes undefined if this function returns 0.
```
Comment (real-or-random) [inline include/secp256k1.h]: Can we say "unspecified"? "Undefined" comes with that weird terrifying sound of undefined behavior.

File: src/secp256k1.c (hunk 3 above)
Comment (jonasnick) [reply src/secp256k1.c]: fixed

**Comment by jonasnick** [comment]
@real-or-random  I added a commit that rephrases the docs. Let me know if you think that's better.

(Also, I replaced `secp256k1_rand256_test` with `secp256k1_rand256` because the former is apparently not random, may produce invalid seckeys and travis randomly hit that in one of the test configurations).

File: src/tests.c [hunk 5]
```diff
@@ -1117,16 +1117,43 @@ void run_scalar_tests(void) {
...
+        secp256k1_scalar_set_b32(&scalar, bin, &overflow);
+        CHECK(overflow == 1);
+        CHECK(secp256k1_scalar_is_zero(&scalar));
+
+        /* A scalar with value of the curve order minus one should not overflow. */
+        bin[31] -= 1;
+        secp256k1_scalar_set_b32(&scalar, bin, &overflow);
+        CHECK(overflow == 0);
+        secp256k1_scalar_get_b32(bin_tmp, &scalar);
+        CHECK(memcmp(bin, bin_tmp, 32) == 0);
```
[the remark this answers is not in the document]
Comment (jonasnick) [reply src/tests.c]: It's probably the only roundtrip because it's the only one which doesn't overlow and which can not be easily tested with `scalar_is_zero`.

**Comment by jonasnick** [comment]
Removed the (attempted) constant time AND in `set_b32_seckey` as per @sipa's suggestion

**Comment by real-or-random** [comment]
Is there a reason to believe that this will break downstream code (because it changes the API)?

File: include/secp256k1.h [hunk 6]
```diff
@@ -597,57 +611,85 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_negate(
...
  * Args:   ctx:    pointer to a context object (cannot be NULL).
- * In/Out: seckey: pointer to a 32-byte private key.
- * In:     tweak:  pointer to a 32-byte tweak.
- */
+ * In/Out: seckey: pointer to a 32-byte secret key. If this function returns 0,
+ *                 seckey will be some unspecified value. (cannot be NULL).
+ * In:     tweak:  pointer to a 32-byte tweak. Must be in the same range as secret
+ *                 keys (see secp256k1_ec_seckey_verify). For uniformly random
+ *                 32-byte arrays the chance of being out of range is
+ *                 negligible (around 1 in 2^128). (cannot be NULL)
```
Comment (dr-orlovsky) [inline include/secp256k1.h]: while the changes are negligible, if one is aimed to write a deterministic code (like in the case of rust wrapper), it may be good to cover this case as well. 

It is possible to add to the docs that in case `tweak`<Z_p, the function will return 0?
Also, do you see any value of differentiating between `tweak`<Z_p and point at infinity cases? Right now both will return 0, but from the end-user perspective the first case requires change of the tweaking factor, while the second may be solved just by using a different public key...

Comment (real-or-random) [reply include/secp256k1.h]: > while the changes are negligible, if one is aimed to write a deterministic code (like in the case of rust wrapper), it may be good to cover this case as well.

Believe me, you don't care about a failure probability of 2^-128. It's astronomically small. It's much smaller than the probability of a hardware error (e.g., RAM returns wrong value). You can simply abort in this case.

File: include/secp256k1.h (hunk 1 above)
Comment (apoelstra) [reply include/secp256k1.h]: Also, missing an `)` after "32-byte arrays". (This was a preexisting problem but we should fix it now.)

File: include/secp256k1.h (hunk 2 above)
Comment (apoelstra) [reply include/secp256k1.h]: same `)` issue here

File: src/tests.c [hunk 7]
```diff
@@ -3994,6 +3994,16 @@ void run_eckey_edge_case_test(void) {
     CHECK(secp256k1_ec_pubkey_tweak_mul(ctx, &pubkey, ctmp2) == 0);
     CHECK(memcmp(&pubkey, zeros, sizeof(pubkey)) == 0);
     memcpy(&pubkey, &pubkey2, sizeof(pubkey));
+    /* Overflowing key zeroizes */
+    memcpy(ctmp, orderc, 32);
+    memset(ctmp2, 0, 32);
+    ctmp2[31] = 0x01;
+    CHECK(secp256k1_ec_seckey_verify(ctx, ctmp2) == 1);
+    CHECK(secp256k1_ec_privkey_tweak_add(ctx, ctmp, ctmp2) == 0);
```
Comment (apoelstra) [inline src/tests.c]: Can you add a check with `ctmp` and `ctmp2` swapped? Or maybe there is little value in this since both of these are invalid.

**Comment by gmaxwell** [comment]
@jonasnick  the _test rng's are biased intentionally to hit corner cases and it worked perfectly there if it detected that your scalar generation was generating an invalid scalar.  Maybe you want random_scalar_order_test  or random_scalar_order instead?   It's better to make the tests not fail even with rare values because they can also be moved over to smaller groups where the failures would be common.

File: include/secp256k1.h (hunk 1 above)
Comment (jonasnick) [reply include/secp256k1.h]: @apoelstra should be fixed in the latest commit.

File: src/tests.c (hunk 7 above)
Comment (jonasnick) [reply src/tests.c]: Are you suggesting to test this function with an overflowing tweak? That should happen a couple of lines below. I pushed a commit to make the comments more clear.

**Comment by jonasnick** [comment]
@gmaxwell Thanks, `random_scalar_order` is almost what I was looking for and agree that it's better than `rand256`. I added a function similar to `random_scalar_order` but returning a byte array.

**Comment by real-or-random** [comment]
Can you squash this?

**Comment by jonasnick** [comment]
Rebasing required a bit of thought due to #710. Please have a look.

**Comment by jonasnick** [comment]
I improved `ecdsa_sign`'s uses of `secp256k1_scalar_set_b32_seckey` a little bit.

File: src/tests.c [hunk 8]
```diff
@@ -3936,45 +3989,64 @@ void run_eckey_edge_case_test(void) {
...
     /* Multiply tweak of zero zeroizes the output. */
-    CHECK(secp256k1_ec_privkey_tweak_mul(ctx, ctmp, ctmp2) == 0);
+    CHECK(secp256k1_ec_seckey_tweak_mul(ctx, ctmp, ctmp2) == 0);
     CHECK(memcmp(zeros, ctmp, 32) == 0);
     CHECK(secp256k1_ec_pubkey_tweak_mul(ctx, &pubkey, ctmp2) == 0);
     CHECK(memcmp(&pubkey, zeros, sizeof(pubkey)) == 0);
     memcpy(&pubkey, &pubkey2, sizeof(pubkey));
-    /* Overflowing key tweak zeroizes. */
+    /* If seckey_tweak_add or seckey_tweak_mul are called with an overflowing
+    seckey, the seckey is zeroized. */
```
Comment (real-or-random) [inline src/tests.c]: Here they're not called with an overflowing seckey but the resulting seckey would overflow.

File: src/scalar_impl.h [hunk 9]
```diff
@@ -55,6 +55,12 @@ static void secp256k1_scalar_order_get_num(secp256k1_num *r) {
 }
 #endif
 
+static int secp256k1_scalar_set_b32_seckey(secp256k1_scalar *r, const unsigned char *bin) {
+  int overflow;
+  secp256k1_scalar_set_b32(r, bin, &overflow);
+  return (!overflow) & (!secp256k1_scalar_is_zero(r));
```
Comment (real-or-random) [inline src/scalar_impl.h]: nit: indentation
I only point it out here but it's wrong in many functions you added.

File: include/secp256k1.h [hunk 10]
```diff
@@ -569,20 +572,31 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_seckey_verify(
...
+ *                      If this function returns 0, seckey will be some
+ *                      unspecified value. (cannot be NULL)
  */
+SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_seckey_negate(
+    const secp256k1_context* ctx,
+    unsigned char *seckey
+) SECP256K1_ARG_NONNULL(1) SECP256K1_ARG_NONNULL(2);
+
+/** Same as secp256k1_ec_seckey_negate, but DEPRECATED. Will be removed in
+ *  future versions. */
```
Comment (real-or-random) [inline include/secp256k1.h]: Can you change the calls in the codebase to  the `seckey` variants? For example https://github.com/bitcoin-core/secp256k1/blob/master/src/valgrind_ctime_test.c#L76

File: include/secp256k1.h [hunk 11]
```diff
@@ -599,57 +613,85 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_negate(
     secp256k1_pubkey *pubkey
 ) SECP256K1_ARG_NONNULL(1) SECP256K1_ARG_NONNULL(2);
 
-/** Tweak a private key by adding tweak to it.
- * Returns: 0 if the tweak was out of range (chance of around 1 in 2^128 for
- *          uniformly random 32-byte arrays, or if the resulting private key
- *          would be invalid (only when the tweak is the complement of the
- *          private key). 1 otherwise.
+/** Tweak a secret key by adding tweak to it.
```
Comment (real-or-random) [inline include/secp256k1.h]: nit: Now that you're rewriting those, can you add an empty line here? (same for the other tweak functions)

File: src/eckey_impl.h [hunk 12]
```diff
@@ -54,10 +54,7 @@ static int secp256k1_eckey_pubkey_serialize(secp256k1_ge *elem, unsigned char *p
 
 static int secp256k1_eckey_privkey_tweak_add(secp256k1_scalar *key, const secp256k1_scalar *tweak) {
     secp256k1_scalar_add(key, key, tweak);
-    if (secp256k1_scalar_is_zero(key)) {
-        return 0;
-    }
-    return 1;
```
Comment (real-or-random) [inline src/eckey_impl.h]: Huh, shouldn't this have been caught by the new constant time test?

File: include/secp256k1.h [hunk 13]
```diff
@@ -599,57 +613,85 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_negate(
...
     const unsigned char *tweak
 ) SECP256K1_ARG_NONNULL(1) SECP256K1_ARG_NONNULL(2) SECP256K1_ARG_NONNULL(3);
 
 /** Tweak a public key by adding tweak times the generator to it.
- * Returns: 0 if the tweak was out of range (chance of around 1 in 2^128 for
- *          uniformly random 32-byte arrays, or if the resulting public key
- *          would be invalid (only when the tweak is the complement of the
- *          corresponding private key). 1 otherwise.
+ * Returns: 0 if the resulting public key would be invalid (only when the tweak
+ *          is the negation of the corresponding secret key). 1 otherwise.
```
Comment (real-or-random) [inline include/secp256k1.h]: What if the tweak itself is out of range?

File: include/secp256k1.h [hunk 14]
```diff
@@ -569,20 +572,31 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_seckey_verify(
...
-/** Negates a private key in place.
+/** Negates a secret key in place.
  *
- *  Returns: 1 always
+ *  Returns: 0 if the given secret key is invalid according to
+ *           secp256k1_ec_seckey_verify. 1 otherwise
  *  Args:   ctx:        pointer to a context object
- *  In/Out: seckey:     pointer to the 32-byte private key to be negated (cannot be NULL)
+ *  In/Out: seckey:     pointer to the 32-byte secret key to be negated. The secret
+ *                      key should be valid according to secp256k1_ec_seckey_verify.
```
Comment (real-or-random) [inline include/secp256k1.h]: nit: "should" is somewhat imprecise. suggestion: "If the secret key is invalid according to secp256k1_ec_seckey_verify, this function returns 0 and seckey will be set to some  unspecified value."

File: include/secp256k1.h [hunk 15]
```diff
@@ -599,57 +613,85 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_negate(
...
- *          would be invalid (only when the tweak is the complement of the
- *          private key). 1 otherwise.
+/** Tweak a secret key by adding tweak to it.
+ * Returns: 0 if the resulting secret key would be invalid (only when the tweak
+ *          is the negation of the secret key). 1 otherwise.
  * Args:    ctx:    pointer to a context object (cannot be NULL).
- * In/Out:  seckey: pointer to a 32-byte private key.
- * In:      tweak:  pointer to a 32-byte tweak.
- */
+ * In/Out:  seckey: pointer to a 32-byte secret key. The secret key should be
```
Comment (real-or-random) [inline include/secp256k1.h]: same as above

File: include/secp256k1.h [hunk 16]
```diff
@@ -599,57 +613,85 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_negate(
     secp256k1_pubkey *pubkey
 ) SECP256K1_ARG_NONNULL(1) SECP256K1_ARG_NONNULL(2);
 
-/** Tweak a private key by adding tweak to it.
- * Returns: 0 if the tweak was out of range (chance of around 1 in 2^128 for
- *          uniformly random 32-byte arrays, or if the resulting private key
- *          would be invalid (only when the tweak is the complement of the
- *          private key). 1 otherwise.
+/** Tweak a secret key by adding tweak to it.
+ * Returns: 0 if the resulting secret key would be invalid (only when the tweak
```
Comment (real-or-random) [inline include/secp256k1.h]: What if the tweak itself is out of range?

File: include/secp256k1.h [hunk 17]
```diff
@@ -599,57 +613,85 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_negate(
...
+ *          is the negation of the secret key). 1 otherwise.
  * Args:    ctx:    pointer to a context object (cannot be NULL).
- * In/Out:  seckey: pointer to a 32-byte private key.
- * In:      tweak:  pointer to a 32-byte tweak.
- */
+ * In/Out:  seckey: pointer to a 32-byte secret key. The secret key should be
+ *                  valid according to secp256k1_ec_seckey_verify. If this
+ *                  function returns 0, seckey will be some unspecified
+ *                  value. (cannot be NULL)
+ * In:       tweak: pointer to a 32-byte tweak. Must be in the same range as secret
```
Comment (real-or-random) [inline include/secp256k1.h]: "must" is similar to "should" here. I guess it's better to specify the consequences if it's not in range, then the function will return 0.

File: include/secp256k1.h [hunk 18]
```diff
@@ -551,7 +551,10 @@ SECP256K1_API int secp256k1_ecdsa_sign(
     const void *ndata
 ) SECP256K1_ARG_NONNULL(1) SECP256K1_ARG_NONNULL(2) SECP256K1_ARG_NONNULL(3) SECP256K1_ARG_NONNULL(4);
 
-/** Verify an ECDSA secret key.
+/** Verify an ECDSA secret key. It is valid if it is not 0 and less than the
```
[the remark this answers is not in the document]
Comment (jonasnick) [reply include/secp256k1.h]: fixed

File: include/secp256k1.h [hunk 19]
```diff
@@ -551,7 +551,10 @@ SECP256K1_API int secp256k1_ecdsa_sign(
...
+ *  secp256k1 curve order when interpreted as an integer (most significant byte
+ *  first). The probability of choosing a 32-byte string at random which is an
```
[the remark this answers is not in the document]
Comment (jonasnick) [reply include/secp256k1.h]: fixed

File: include/secp256k1.h [hunk 20]
```diff
@@ -599,57 +613,85 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_negate(
...
- * In:      tweak:  pointer to a 32-byte tweak.
- */
+ * In/Out:  seckey: pointer to a 32-byte secret key. The secret key should be
+ *                  valid according to secp256k1_ec_seckey_verify. If this
+ *                  function returns 0, seckey will be some unspecified
+ *                  value. (cannot be NULL)
+ * In:       tweak: pointer to a 32-byte tweak. Must be in the same range as secret
+ *                  keys (see secp256k1_ec_seckey_verify). For uniformly random
+ *                  32-byte arrays the chance of being out of range is
+ *                  negligible (around 1 in 2^128). (cannot be NULL)
```
[the remark this answers is not in the document]
Comment (jonasnick) [reply include/secp256k1.h]: I don't understand what you're suggesting. Yes, the tweak must be in range. The resulting seckey will be in range if the tweak is not the negation of the seckey.

File: src/secp256k1.c [hunk 21]
```diff
@@ -471,7 +471,7 @@ int secp256k1_ecdsa_sign(const secp256k1_context* ctx, secp256k1_ecdsa_signature
     secp256k1_scalar r, s;
     secp256k1_scalar sec, non, msg;
     int ret = 0;
-    int overflow = 0;
+    int is_sec_valid;
```
[the remark this answers is not in the document]
Comment (jonasnick) [reply src/secp256k1.c]: Afaics it's just wasted work if we fix the duplicated recovery code. Better to make recovery use the common code in a separate PR (right after this one).

File: src/tests.c (hunk 8 above)
Comment (jonasnick) [reply src/tests.c]: No, seckey is equal to orderc which is overflowing. Added `CHECK(secp256k1_ec_seckey_verify(ctx, ctmp) == 0);`

File: src/scalar_impl.h (hunk 9 above)
Comment (jonasnick) [reply src/scalar_impl.h]: Ugh, fixed, but only saw this in one other function (run_scalar_set_b32_seckey_tests)

File: include/secp256k1.h (hunk 10 above)
Comment (jonasnick) [reply include/secp256k1.h]: Done

File: include/secp256k1.h (hunk 11 above)
Comment (jonasnick) [reply include/secp256k1.h]: Done

File: src/eckey_impl.h (hunk 12 above)
Comment (jonasnick) [reply src/eckey_impl.h]: Presumably the compiler optimized away the branching

File: include/secp256k1.h (hunk 13 above)
Comment (jonasnick) [reply include/secp256k1.h]: Added a commit to clarify

File: include/secp256k1.h (hunk 14 above)
Comment (jonasnick) [reply include/secp256k1.h]: fixed in separate commit

File: include/secp256k1.h (hunk 15 above)
Comment (jonasnick) [reply include/secp256k1.h]: fixed

File: include/secp256k1.h (hunk 16 above)
Comment (jonasnick) [reply include/secp256k1.h]: fixed

File: include/secp256k1.h (hunk 17 above)
Comment (jonasnick) [reply include/secp256k1.h]: fixed

File: src/secp256k1.c [hunk 22]
```diff
@@ -556,17 +554,23 @@ int secp256k1_ec_pubkey_create(const secp256k1_context* ctx, secp256k1_pubkey *p
...
     secp256k1_scalar_negate(&sec, &sec);
     secp256k1_scalar_get_b32(seckey, &sec);
 
     secp256k1_scalar_clear(&sec);
-    return 1;
+    return ret;
+}
+
+int secp256k1_ec_privkey_negate(const secp256k1_context* ctx, unsigned char *seckey) {
+  return secp256k1_ec_seckey_negate(ctx, seckey);
```
Comment (real-or-random) [inline src/secp256k1.c]: nit: indentation

File: src/secp256k1.c [hunk 23]
```diff
@@ -605,6 +609,10 @@ int secp256k1_ec_privkey_tweak_add(const secp256k1_context* ctx, unsigned char *
     return ret;
 }
 
+int secp256k1_ec_privkey_tweak_add(const secp256k1_context* ctx, unsigned char *seckey, const unsigned char *tweak) {
+  return secp256k1_ec_seckey_tweak_add(ctx, seckey, tweak);
```
Comment (real-or-random) [inline src/secp256k1.c]: here too

File: src/secp256k1.c [hunk 24]
```diff
@@ -649,6 +657,10 @@ int secp256k1_ec_privkey_tweak_mul(const secp256k1_context* ctx, unsigned char *
     return ret;
 }
 
+int secp256k1_ec_privkey_tweak_mul(const secp256k1_context* ctx, unsigned char *seckey, const unsigned char *tweak) {
+  return secp256k1_ec_seckey_tweak_mul(ctx, seckey, tweak);
```
Comment (real-or-random) [inline src/secp256k1.c]: same

File: include/secp256k1.h [hunk 25]
```diff
@@ -599,57 +616,93 @@ SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_negate(
...
- *          uniformly random 32-byte arrays, or if the resulting private key
- *          would be invalid (only when the tweak is the complement of the
- *          private key). 1 otherwise.
- * Args:    ctx:    pointer to a context object (cannot be NULL).
- * In/Out:  seckey: pointer to a 32-byte private key.
- * In:      tweak:  pointer to a 32-byte tweak.
- */
+/** Tweak a secret key by adding tweak to it.
+ *
+ *  Returns: 0 if the arguments are invalid or resulting secret key would be
```
Comment (real-or-random) [inline include/secp256k1.h]:
```suggestion
 *  Returns: 0 if the arguments are invalid or the resulting secret key would be
```

File: src/secp256k1.c (hunk 22 above)
Comment (jonasnick) [reply src/secp256k1.c]: fixed

File: src/secp256k1.c (hunk 23 above)
Comment (jonasnick) [reply src/secp256k1.c]: fixed

File: src/secp256k1.c (hunk 24 above)
Comment (jonasnick) [reply src/secp256k1.c]: fixed

File: include/secp256k1.h (hunk 25 above)
Comment (jonasnick) [reply include/secp256k1.h]: fixed

**Comment by jonasnick** [comment]
@apoelstra would you mind reACKing?
