### PR TITLE
build: 45839th attempt to fix symbol visibility on Windows

### LINKED ISSUE #1421: mingw-w64: "visibility attribute not supported in this configuration; ignored" under `-flto`
Building master (b10ddd2bd2bdce9ca8f2d4733636a9d9e7ac3da1):
```bash
# x86_64-w64-mingw32-gcc (GCC) 12-win32
./autogen.sh
./configure --host=x86_64-w64-mingw32 CFLAGS="-flto" LDFLAGS="-flto"
make -j9
<snip>
src/secp256k1.c: In function 'secp256k1_context_create':
src/secp256k1.c:149:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
  149 | }
      | ^
src/secp256k1.c: In function 'secp256k1_context_preallocated_clone':
src/secp256k1.c:160:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
  160 | }
      | ^
src/secp256k1.c: In function 'secp256k1_context_clone':
src/secp256k1.c:173:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
  173 | }
      | ^
src/secp256k1.c: In function 'secp256k1_context_preallocated_destroy':
src/secp256k1.c:184:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
  184 | }
      | ^
src/secp256k1.c: In function 'secp256k1_context_destroy':
src/secp256k1.c:196:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
  196 | }
      | ^
src/secp256k1.c: In function 'secp256k1_ec_pubkey_parse':
src/secp256k1.c:288:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
  288 | }
      | ^
src/secp256k1.c: In function 'secp256k1_ec_pubkey_serialize':
src/secp256k1.c:311:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
  311 | }
      | ^
< similar output continues>
```

Wanted to raise this, as Core may eventually go down the LTO route (https://github.com/bitcoin/bitcoin/pull/25391), and `-flto` will be getting passed down.

### PR DESCRIPTION
**Pull request by real-or-random**
Fixes #1421. See code comments for rationale. 

Related meta-bug: #1181.  This reminds me that we should move forward with #1359.

### CODE REVIEW

**Comment by fanquake** [comment]
I can at least confirm that this "fixes" the output I was seeing in #1421. The most recent comment on the upstream GCC issue is not 100% clear to me.

**Comment by real-or-random** [comment]
> The most recent comment on the upstream GCC issue is not 100% clear to me.

Can you elaborate on which part is unclear? 

In any case, I could rephrase this such that it says it's a GCC bug. When I wrote it, I wasn't sure yet, but the upstream response seems to confirm that this is a bug.

**Comment by fanquake** [comment]
I've re-read, and yes, it seems like the conclusion is that it is a GCC issue. I guess what is actually unclear is if/when anyone might fix it upstream.

**Comment by real-or-random** [comment]
Okay. I've nevertheless rephrased the comment to make it (hopefully) clearer.

**Comment by fanquake** [comment]
ACK 447334cb06de229024161021cc79b3af32ce8b5c

**Comment by real-or-random** [comment]
@hebasto Wanna review this? :)

**Comment by fanquake** [comment]
also cc @theuni

File: include/secp256k1.h [hunk 1]
```diff
@@ -147,6 +147,15 @@ typedef int (*secp256k1_nonce_function)(
      * 1. If using Libtool, it defines DLL_EXPORT automatically.
      * 2. In other cases, SECP256K1_DLL_EXPORT must be defined. */
 #   define SECP256K1_API extern __declspec (dllexport)
+#  else
+    /* Building libsecp256k1 as a static library on Windows.
```
Comment (hebasto) [inline include/secp256k1.h:151]: nit: Referencing the use of a static library does not apply to our cases with the `tests` and `noverify_tests` targets, where object files are linked directly.

**Review by hebasto — APPROVED** [review]
ACK 447334cb06de229024161021cc79b3af32ce8b5c, tested on Ubuntu 24.04 using the following commands:
```
$ env CFLAGS="-flto" cmake -B build --preset dev-mode --toolchain cmake/x86_64-w64-mingw32.toolchain.cmake
$ cmake --build build -j 16 -t tests noverify_tests
```

File: include/secp256k1.h (hunk 1 above)
Comment (real-or-random) [reply include/secp256k1.h:151]: You mean https://github.com/bitcoin-core/secp256k1/blob/master/src/CMakeLists.txt#L89, right? True, and it's also true for `bench_internal` and `bench_ecmult`. 

Would you prefer "Building libsecp256k1 not as a DLL."? (I dropped the Windows part because it's anyway only Windows in the outer #ifdef.)

Comment (real-or-random) [reply include/secp256k1.h:151]: > Looks good. However, I'm not sure if it worth invalidating all ACKs.

Ok, let's just get it merged.
